---
functional:
  - Должна быть возможность соревнования между двумя игроками в режиме реального времени
  - Игроки должны видеть код друг друга во время соревнования
  - Должна быть возможность игры с ботом
  - Должна быть возможность игры с другом по ссылке
  - Должна быть система рейтингов игроков
non-functional:
  - Сайт должен быть удобным в использовании и оптимизированным для скорости работы
  - Сайт должен обеспечивать безопасность и защиту данных пользователей
  - Сайт должен быть адаптирован для мобильных устройств
  - Сайт должен корректно работать в последних версиях браузеров
  - Сайт должен поддерживать одновременную работу 1000 пользователей
implicit:
  - Интерфейс должен быть интуитивно понятным для пользователей
  - Ошибки и некорректные действия должны сопровождаться понятными сообщениями
  - Должны быть предусмотрены механизмы предотвращения и обработки читерства
  - Должны быть учтены возможности расширения и модификации функционала
